### ISSUE TITLE
Vamos fazer uma image docker também?

### ISSUE THREAD

**Issue by hermesalvesbr** [paulocsilvajr/scripts-servidor-esus#1]
Olá Paulo,

Estou iniciando uma imagem docker com o esus, alpha ainda, mas acho que podemos unir forçar.

https://hub.docker.com/repository/docker/softagon/esus_ab

Seus script podem melhorar e muito meu trabalho na imagem.

**Comment by paulocsilvajr** [comment]
Tudo bem Hermes,

Os scripts estão públicos, pode usar a vontade e adaptar a seu caso. Eu fiz testes somente em Máquinas Virtuais Ubuntu a partir da versão 18.04, mas aparentemente estão funcionando corretamente.
Sobre rodar em um container, havia tido problemas com o systemd, que é uma exigência ao tentar instalar pelo instalador oficial do e-SUS(https://sisaps.saude.gov.br/esus/).
Se precisar de alguma ajuda, é só me contatar.

**Comment by hermesalvesbr** [comment]
Obrigado pelo retorno! 

Nesta versão Alpha já resolvi o systemd. Estou com pendência pra instalar ao ligar o container. 

Da uma testada aí , você vai ver que tem 2 Scripts um install e iniciar. 

Quer q eu te mande o docker compose.yml?

**Comment by paulocsilvajr** [comment]
Hermes, me envie então o docker-compose.yml para eu ver.
Vou testar o container também e te dou um retorno.

**Comment by hermesalvesbr** [comment]
Bom dia,

Segue docker-compose.yml

```
# sudo java -jar eSUS-AB-PEC-4.5.6-Linux64.jar -console -url="jdbc:postgresql://teste_esus_postgres:5432/bancoesus" -username="bancoesus" -password="BR45RhXnX3Mv0Es"
version: '3'
services:
  esus:
    tty: true
    image: 'softagon/esus_ab:alpha'
    volumes:
      - /src/apps/esus/opt:/opt/e-SUS/
    command:
      - /home/install.sh
    ports:
      - '8080:8080'
    networks:
      - esus
      - proxy
    environment:
      POSTGRES_HOST: 'esus_ab_postgres'
      POSTGRES_USER: bancoesus
      POSTGRES_PASSWORD: 'BR45RhXnX3Mv0Es'
      POSTGRES_DB: bancoesus
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: bancoesus
      POSTGRES_PASSWORD: 'BR45RhXnX3Mv0Es'
      PGDATA: /data/postgres
    volumes:
      - /src/apps/esus/banco/postgres:/data/postgres
      - /src/apps/esus/banco/datapg:/var/lib/postgresql/data
    ports:
      - "55457:5432"
    networks:
      - esus
      - proxy
networks:
  esus:
  proxy:
```

**Comment by paulocsilvajr** [comment]
Hermes, boa tarde
Me desculpe pela demorar do feedback.
Executei o container via docker-composer que você passou, mas estou com dúvidas de como eu faço para deixar o container do e-SUS operacional

**Comment by hermesalvesbr** [comment]
Roda o install.sh que está dentro do container.

Em ter., 28 de jun. de 2022 16:09, Paulo Carvalho da Silva Junior <
***@***.***> escreveu:

**Comment by paulocsilvajr** [comment]
Está solicitando a senha para o usuário docker. Executei o "install.sh" sem sudo.

**Comment by hermesalvesbr** [comment]
A senha é docker

**Comment by paulocsilvajr** [comment]
Blz Hermes, já anotei, pode apagar a mensagem. Obrigado. Vou testar melhor agora.
